# name: Custom Light
# author: Rakosn1cek
# blurb: A custom light theme variants for bright environments.

foreground            #000000
background            #dee3da
selection_foreground  #5f7eff
selection_background  #37474f

# Cursor colours
cursor                #7b009e
cursor_text_color     #7b009e

# URL underline colour when hovering
url_color             #00897b

# The basic 16 colours

# black
color0 #000000
color8 #616161

# red
color1 #d32f2f
color9 #d32f2f

# green
color2  #388e3c
color10 #388e3c

# yellow
color3  #000000
color11 #616161

# blue
color4  #0a3aff
color12 #6095ff

# magenta
color5  #000000
color13 #616161

# cyan
color6  #000000
color14 #616161

# white
color7  #000000
color15 #37474f
