# name: Hacker Movie
# author: Rakosn1cek
# blurb: Classic Hollywood terminal green-screen style.

foreground            #00ff00
background            #000000
selection_foreground  #000000
selection_background  #00ff00

# Cursor colours (glowing green block)
cursor                #00ff00
cursor_text_color     #000000

# URL underline colour when hovering
url_color             #39ff14

# The basic 16 colours

# black (deep blacks and dark forest greens for UI borders)
color0 #000000
color8 #005900

# red (glitch alert red)
color1 #ff003c
color9 #ff3366

# green (bright terminal green and glowing phosphor green)
color2  #00cc00
color10 #00ff00

# yellow (amber warning shades)
color3  #ccff00
color11 #ffff00

# blue (matrix code data stream shades)
color4  #00dd00
color12 #39ff14

# magenta (cyberpunk purple accents)
color5  #800080
color13 #ff00ff

# cyan (matrix terminal diagnostic shades)
color6  #00aa55
color14 #00ffaa

# white (dim green-tinted whites for secondary text)
color7  #a0cca0
color15 #daffda
