# --- VISUALS ---
font_family      JetBrainsMono Nerd Font
font_size        10.0
window_padding_width 15
background_opacity 0.8
#background_blur 1
cursor_shape underline
cursor_underline_thickness 2.0
cursor_shape underline
cursor_trail 1
cursor_trail_decay 0.1 0.4
cursor_beam_thinckness 1.5

# --- CLEAN UI ---
hide_window_decorations yes
confirm_os_window_close 0
cursor_blink yes
enable_audio_bell no

# --- TABS ---
tab_bar_style       powerline
tab_powerline_style slanted

# --- OTHER SETTINGS ---
allow_remote_control yes
listen_on unix:@mykitty


# BEGIN_KITTY_THEME
# Cyberpunk Neon
include current-theme.conf
# END_KITTY_THEME

shell_integration no-cursor


