########################################################################################
# HYPRLAND DYNAMIC CONFIG (MASTER+SCROLLING LAYOUT)
########################################################################################
source = /home/rk1/.cache/wal/colors-hyprland.conf

# --- 1. SOURCES & ENV ---
env = GDK_BACKEND,wayland
env = QT_QPA_PLATFORM,wayland;xcb
env = CLUTTER_BACKEND,wayland
env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_TYPE,wayland
env = XDG_SESSION_DESKTOP,Hyprland
env = WLR_NO_HARDWARE_CURSORS,1
env = WLR_RENDERER_ALLOW_SOFTWARE,1
env = TERMINAL,kitty
env = LIBVA_DRIVER_NAME,iHD

# --- 2. MONITOR & INPUT ---
monitor=,preferred,auto,1.0

input {
    kb_layout = us
    follow_mouse = 1
    sensitivity = 0 
touchpad {
    natural_scroll = no
    tap-to-click = true
    tap-and-drag = true
    }
}
cursor {
    no_hardware_cursors = true
}

misc {
    # vfr = true  # Enables Variable Frame Rate to save CPU cycles
    disable_hyprland_logo = true
}

# --- 3. VARIABLES ---
$mainMod = SUPER
$altMod = ALT
$terminal = kitty
$backup_terminal = foot
$filemanager = thunar

# Source external config files
source = ~/.config/hypr/configs/autostart.conf
source = ~/.config/hypr/configs/keybinds.conf
source = ~/.config/hypr/configs/windowrules.conf

# --- 5. LOOK & FEEL ---
general {
    gaps_in = 5
    gaps_out = 5
    layout = master
    }

master {
	new_status = slave
	new_on_active = none
	new_on_top = false
	mfact = 0.55
	orientation = left
	special_scale_factor = 1.mc colors-h0
	slave_count_for_center_master = 2
}
scrolling {
    column_width = 0.9
    fullscreen_on_one_column = true
    # direction can be right, left, up, or down
    direction = right 
}
workspace = 4, layout:scrolling
# 3-finger swipe left moves the infinite tape to the right (next window)
gesture = 3, left, dispatcher, layoutmsg, move +col

# 3-finger swipe right moves the infinite tape to the left (previous window)
gesture = 3, right, dispatcher, layoutmsg, move -col

decoration {
    rounding = 0    
    active_opacity = 1
    inactive_opacity = 1
    fullscreen_opacity = 1
    
blur {
    enabled = false
    size = 8
    new_optimizations = true
    }
   
shadow {
    enabled = false
    range = 15
    render_power = 4
    color = rgba(255, 255, 255, 0.6)
    }

animations {
    bezier = myBezier, 0.05, 0.9, 0.1, 1.05
    animation = windows, 1, 7, myBezier
    animation = workspaces, 1, 7, default
    animation = layers, 1, 15, myBezier, slide
}
}
