[colors2]
background=ffffff
foreground=4c4f69

# Black
regular0=5c5f77
bright0=6c6f85

# Red
regular1=d20f39
bright1=d20f39

# Green
regular2=40a02b
bright2=40a02b

# Yellow (Much darker and readable)
regular3=df8e1d
bright3=df8e1d

# Blue
regular4=1e66f5
bright4=1e66f5

# Magenta
regular5=ea76cb
bright5=ea76cb

# Cyan
regular6=179299
bright6=179299

# White
regular7=acb0be
bright7=bcc0cc
