# --- WINDOW RULES 0.54+ ---
# Widgets Rules
windowrule {
	name = cpanel-widget
	match:class = cpanel-widget.py
	xray = on
}
windowrule {
	name = wallpaper-widget
	match:class = changewall-widget.py
	animation = slide bottom
	xray = on
}
windowrule {
	name = battery-widget
	match:class = battery-widget.py
	move = 1485 40
	animation = slide right
	xray = on
}
windowrule {
	name = notif-widget
	match:class = notif-widget.py
	move = 1450 40
	animation = slide right
	xray = on
}
windowrule {
	name = sys-info
	match:class = sysmon-widget.py
	move = 1530 40
	animation = slide right
	xray = on
}

# App Launcher & Clipboard
windowrule {
	name = notifications
	match:class = dunst
	opacity = 0.8 0.8
}
# Music Widget
windowrule {
    name = music-player
    match:class = music
    size = 1000 450
    move = 0 60
    center = on
}

# System & Terminal Tools
windowrule {
    name = kitty
    match:class = kitty
    opacity = 0.9 0.9
    border_size = 2px
    border_color = @color2
    xray = on
}

# File Managers
windowrule {
    name = file-managers
    match:class = thunar|yazi
    animation = fade
    opacity = 0.7 0.7
    border_color = @color2
    border_size = 2px
}

# Editors & Tools
windowrule {
    name = geany-rule
    match:class = geany
    animation = fade
    border_color = @color2
    border_size = 2px
}
windowrule {
    name = qalculate-rule
    match:class = qalculate-gtk
    animation = slide
    opacity = 0.7 0.7
}
windowrule {
	name = browsers
	match:class = falcon
	workspace = 1
	border_size = 2px
	border_color = @color2
}
windowrule {
    name = min-browser
    match:class = Min
    workspace = 1
    opacity = 0.8 0.8
    xray = on
    border_size = 2px
    border_color = @color2
}
windowrule {
    name = save-open-rule
    match:title = ^.*(Save|Open).*$
    stay_focused = on
    float = on
    center = on
}
windowrule {
	name = rtm
	match:class = rtm
	float = on
	size = 740 780
	center = on
	workspace = 3
	move = 0 60
	border_size = 2px
	xray = on
}
windowrule {
    name = budget-buddy
    match:class = budget-buddy
    float = on
    size = 740 780
    center = on
    move = 0 60
    workspace = 3
    border_size = 2px
    xray = on
}

# --- 8. NEW 0.53 LAYER RULES ---
layerrule {
	name = notifications
	match:namespace = dunst
	blur = on
}
# Rofi Wallpaper Switcher
# Rofi / Drun Layer
layerrule {
	name = apps-menu
	animation = slide bottom
	blur = on
	ignore_alpha = 0.2
}
# Rofi Power Menu
layerrule {
    name = rofi-cpanel
    animation = slide right
    blur = on
    ignore_alpha = 0.2
}
# Waybar Layer
layerrule {
    name = waybar-layer
    match:namespace = waybar
    blur = on
    no_anim = on
    ignore_alpha = 0.5
}

# Desktop Widgets
# Workspaces
#workspace = s[true], gapsout:0, gapsin:0
#workspace = w[tv1], gapsout:0, gapsin:0
