# --- 7. WINDOW RULES 0.53 ---

#windowrule = tile on, match:workspace special:magic

# App Launcher & Clipboard
# Music Widget
windowrule {
    name = music-player
    match:class = music
    float = on
    size = 1000 450
    move = 0 60
    center = on
}

# System & Terminal Tools
windowrule {
    name = kitty
    match:class = kitty
    float = on
    opacity = 0.9 0.9
    border_size = 1
    border_color = #0abdc6
    xray = on
}

# File Managers
windowrule {
    name = file-managers
    match:class = thunar
    float = on
    animation = fade
    opacity = 0.7 0.7
}

# Editors & Tools
windowrule {
    name = geany-rule
    match:class = geany
    float = on
    animation = fade
}
windowrule {
    name = qalculate-rule
    match:class = qalculate-gtk
    float = on
    size = 600 500 
    animation = slide
    opacity = 0.7 0.7
}
windowrule {
	name = browsers
	match:class = falcon
	workspace = 1
	border_size = 2px
}
windowrule {
    name = min-browser
    match:class = Min
    workspace = 1
    opacity = 0.8 0.8
    xray = on
    border_size = 2px
}
windowrule {
	name = rtm
	match:class = rtm
	float = on
	size = 740 780
	center = on
	workspace = 3
	move = 0 60
	border_size = 0
	xray = on
}
windowrule {
    name = budget-buddy
    match:class = budget-buddy
    float = on
    size = 740 780
    center = on
    move = 0 60
    workspace = 3
    border_size = 0
    xray = on
}

# --- 8. NEW 0.53 LAYER RULES ---

# Rofi / Drun Layer
layerrule {
    name = rofi
    match:namespace = rofi
    animation = slide top
    blur = on
    ignore_alpha = 0.2
}

# Waybar Layer
layerrule {
    name = waybar-layer
    match:namespace = waybar
    blur = on
    no_anim = on
    ignore_alpha = 0.5
}

# Desktop Widgets
layerrule {
    name = system-pod-layer
    match:namespace = ^(org.waybar.pod)$
    blur = on # Usually better for small text widgets
    no_anim = on
}
# Workspaces
#workspace = s[true], gapsout:0, gapsin:0
#workspace = w[tv1], gapsout:0, gapsin:0
