font=JetBrainsMono Nerd Font:size=10:hintstyle=hintslight:rgba=rgb:antialias=true
pad=20x10

[scrollback]
lines=1000

[cursor]
style=underline
blink=yes
underline-thickness=1.5

# Apply to Dark Mode
[colors]
cursor=000000 e6c446
alpha=0.0

# Apply to Light Mode
[colors2]
cursor=000000 e6c446

[main]
include=~/.config/foot/themes/ayu-dark.ini
include=~/.config/foot/themes/ayu-light.ini
letter-spacing=0
line-height=14
