# --- 1. CORE SYSTEM & POLKIT ---
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = /usr/lib/polkit-kde-authentication-agent-1

# --- 2. WAYBAR SETUP ---
exec-once = waybar

# --- 3. THEME & WALLPAPER ---
exec-once = awww-daemon && awww img $(cat ~/.cache/wal/wal)
exec-once = wal -R
exec-once = dunst

# --- 4. HARDWARE & UTILITIES ---
exec-once = brightnessctl set $(cat ~/.cache/brightness_level)
# Replace your current cliphist lines with:
exec-once = bash ~/.config/hypr/scripts/cliphist-start.sh
exec-once = wl-paste --type text --watch cliphist store -max-items 200
exec-once = wl-paste --type image --watch cliphist store -max-items 200
