# --- 1. CORE SYSTEM & POLKIT ---
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = /usr/lib/polkit-kde-authentication-agent-1

# --- 2. THE DUAL-WAYBAR SETUP ---
# Top Bar (The standard one)
exec-once = waybar

# Desktop Bar (Conky-style widget & System info waybar)
#exec-once = G_APPLICATION_ID=org.waybar.desktop waybar -c ~/.config/waybar/config-desktop -s ~/.config/waybar/style-# desktop.css
exec-once = waybar -c ~/.config/waybar/config-pod -s ~/.config/waybar/style-pod.css
# --- 3. THEME & WALLPAPER ---
exec-once = swww-daemon
exec-once = swww img ~/.config/backgrounds/wall.png
exec-once = wal -R
exec-once = pywalfox start
exec-once = swaync

# --- 4. HARDWARE & UTILITIES ---
exec-once = brightnessctl set $(cat ~/.cache/brightness_level)
exec-once = wl-paste --type text --watch cliphist store -max-items 200
exec-once = wl-paste --type image --watch cliphist store -max-items 200
