# --- 7. WINDOW RULES 0.53 ---

#windowrule = tile on, match:workspace special:magic

# App Launcher & Clipboard

# Music Widget
windowrule {
    name = kew-widget
    match:class = ^(musicbox)$
    float = on
    size = 300 350
    pin = on
}

# System & Terminal Tools
windowrule {
    name = system-tools
    match:class = ^(btop|kitty|foot)$
    float = on
    size = 900 780
    move = 0 60
    center = on
    workspace = 2
    opacity = 1 override 1 override
    no_blur = on
    border_size = 0
}

# File Managers
windowrule {
    name = file-managers
    match:class = ^(thunar|dolphin)$
    size = 1000 800
    float = on
    center = on
    animation = fade
    opacity = 0.8 0.8
}

# Editors & Tools
windowrule {
    name = geany-rule
    match:class = geany
    float = on
    size = 950 600
    center = on
    animation = fade
}
windowrule {
    name = qalculate-rule
    match:class = qalculate-gtk
    float = on
    center = on
    animation = slide
    opacity = 0.7 0.7
}
windowrule {
	name = browsers
	match:class = ^(falcon|floorp)$
	workspace = 1
}
windowrule {
	name = rtm-automation
	match:class = ^(rtm)$
	float = on
	size = 800 780
	center = on
	workspace = 3
	move = 0 60
	border_size = 0
}
windowrule {
    name = budget-automation
    match:class = ^(budget-buddy)$
    float = on
    size = 800 780
    center = on
    move = 0 60
    workspace = 3
    border_size = 0
}

# --- 8. NEW 0.53 LAYER RULES ---


# Waybar Layer
layerrule {
	name = rofi
	blur = on
	ignore_alpha = 0.2
}

layerrule {
    name = waybar-layer
    match:namespace = waybar
    blur = on
    no_anim = on
    ignore_alpha = 0.5
}

# Desktop Widgets
layerrule {
    name = desktop-widget-layer
    match:namespace = desktop-widget
    blur = on
    no_anim = on
}

layerrule {
    name = system-pod-layer
    match:namespace = ^(org.waybar.pod)$
    blur = off # Usually better for small text widgets
    no_anim = on
}
# Workspaces
#workspace = s[true], gapsout:0, gapsin:0
#workspace = w[tv1], gapsout:0, gapsin:0
